os:
- linux
- osx
osx_image: xcode8.3

dist: trusty

language: node_js
node_js: '8'

env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - secure: GH_TOKEN="a3OwYvvPu2ws5keFQEfjJFrI1IWkxvmu9/9Uw9w4KxjtCEQqNpQL4EMciZ+PTMPmS1i8r4aLKIB2QikY4MAbxqXUnF8+4mrAgFvKKm6ys3DkQzj/HSCLqkIG6UMR/hhZbOej+FpXeWjgVhCVFS9V52e8e5fz0tu1AtrDYFrBy9YvGbRPugiWAS0H+VzqzRWusqlYXisnPhyU9yps1PYuZVxFBdEzXKp1rFobrU8C7kvZ4oLiEW7TQj1mn+5ZcMtBOHwGSYjN8PJsEjerEFN1XotwbPTUlH29NgV8/h3F8JdfIxuMsXrirVQGFmqP8MTGsTORtCE8umczY0CLm2xPwDarI+i1DCI0vCSRwTYdkWsr387wNpEz4Bk4JTqi62PzX9EvQHaJl1jUIXaJtD6W9WO2Ue7r/qFnvUJC4YxMwp0KCELsQ37kCmDTq6WW2u+gBcJ8OTcMBi3R5SBzcv6msGhR/sSPNiNyo+jg959GnoPCP9hDgA31zRmSkZBdDqEq2sbCZSfA+l58pakHs6X3bKAiLeejlNYQN2ktIpKbU6ngyI8ZbLBwYE25oDMXld3Il4z14K4EQgdh0D0R45oUAR14TIrnhiL6QZ62D+hnuqVXLFy2TKJf7SKV81kYf++7SKtcM96mwjHMyOlRxwgD59oQ+sdkmYNCe2bvPsZeBFk="
addons:
  apt:
    packages:
    - libavahi-compat-libdnssd-dev

cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
install:
- npm install

script:
- npm test
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist -- --mac; fi