image: Visual Studio 2017
# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

platform:
  - x64
environment:
  BONJOUR_HOME: 'C:\Program Files\Bonjour'
  BONJOUR_SDK_HOME: 'C:\Program Files\Bonjour SDK'
  download_user:
    secure: qJc53Aj3IePOJrzM23qw2UzmmHhzw0AfGQmAMUsAc5I=
  bonjour_installer64:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIiSkHpSe7idgVOXufBISjbs
  bonjour_installer:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIghyl9zbrmS6I+8MY1xOkgh
  bonjour_sdk64:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIhP2q0XRDUqXUrSKhvyy/iu
  bonjour_sdk:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIjjzytlZvdLKEiCanjwgvLJ

cache:
  - node_modules
  - vendor
  - '%USERPROFILE%\.electron'
  - '%LocalAppData%\electron-builder\cache'
init:
  - git config --global core.autocrlf input

install:
  - cmd: echo %BONJOUR_SDK_HOME%
  - ps: Get-ChildItem "env:"
  - IF NOT EXIST vendor mkdir vendor
  - IF NOT EXIST C:\projects\stargazer\vendor\Bonjour.msi curl -fsS -u %download_user% -o vendor\Bonjour.msi http://%bonjour_installer%
  - IF NOT EXIST C:\projects\stargazer\vendor\Bonjour64.msi curl -fsS -u %download_user% -o vendor\Bonjour64.msi http://%bonjour_installer64%
  - IF NOT EXIST C:\projects\stargazer\vendor\BonjourSDK64.msi curl -fsS -u %download_user% -o vendor\BonjourSDK64.msi http://%bonjour_sdk64%
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\projects\stargazer\vendor\Bonjour64.msi', /quiet, /qn, /norestart, /l, 'C:\projects\stargazer\install.log' -Wait
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\projects\stargazer\vendor\BonjourSDK64.msi', /quiet, /qn, /norestart, /l, 'C:\projects\stargazer\install_sdk.log' -Wait
  - ps: ls
  - ps: type install.log
  - ps: type install_sdk.log
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run dist
  - npm run candle
  - npm run light

test: off
configuration: Release

artifacts:
  - path: "dist/*.msi"
    name: App
  - path: "*.exe"
    name: Bundle

deploy:
  - provider: GitHub
    auth_token:
      secure: rDaQKugNpZ/X1f1VHPp9pWhHdHnzt5OUJKYB8Y+B0opO2ee8eJW1jgKHL4k9cjnB
    artifact: Bundle
