image: Visual Studio 2017

platform:
  - x64
environment:
  BONJOUR_HOME: 'C:\Program Files (x86)\Bonjour'
  BONJOUR_SDK_HOME: 'C:\Program Files (x86)\Bonjour SDK'
  APPVEYOR_RDP_PASSWORD: Temp_Test_0234
  download_user:
    secure: qJc53Aj3IePOJrzM23qw2UzmmHhzw0AfGQmAMUsAc5I=
  bonjour_installer64:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIiSkHpSe7idgVOXufBISjbs
  bonjour_installer:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIghyl9zbrmS6I+8MY1xOkgh
  bonjour_sdk64:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIhP2q0XRDUqXUrSKhvyy/iu
  bonjour_sdk:
    secure: QbbC1VtR6vZAKfHUJeJ1nnm3Hi0HVrpmS3+ocEwmfIjjzytlZvdLKEiCanjwgvLJ

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - cmd: echo %BONJOUR_SDK_HOME%
  - ps: Get-ChildItem "env:"
  - curl -fsS -u %download_user% -o Bonjour64.msi http://%bonjour_installer64%
  - curl -fsS -u %download_user% -o BonjourSDK64.msi http://%bonjour_sdk64%
  - ps: msiexec /i 'C:\projects\stargazer\Bonjour64.msi' /quiet /qn /norestart /l*v 'C:\projects\stargazer\install.log'
  - ps: msiexec /i 'C:\projects\stargazer\BonjourSDK64.msi' /quiet /qn /norestart /l*v 'C:\projects\stargazer\install_sdk.log'
  - ps: ls
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: type install.log
  - ps: type install_sdk.log
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run dist

test: off

artifacts:
  - path: installer.log
